[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--doctest-modules"

[tool.coverage.run]
source = ["grizly_app"]
omit = ["*/__init__.py", "*/tests/*"]

[tool.coverage.report]
show_missing = true
skip_covered = false
